#language: python
#python:
#  - "3.6"
#install:
#  - pip install -r requirements.txt
#script: pytest

language: node_js
node_js:
  - 9
cache:
  directories:
    - static/node_modules
script:
  - cd static && npm install && npm test
notifications:
    slack: ask-eng:K2sBuzmuU1XHLA9JroSjpsh8