#language: python
#python:
#  - "3.6"
#install:
#  - pip install -r requirements.txt
#script: pytest

language: node_js
node_js:
  - 6
cache:
  directories:
    - static/node_modules
script:
  - cd static && npm run build && npm test